name: build_foxy
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://ros:foxy-ros-base-focal
      
    steps:
    - name: deps
      run: |
        sudo apt update
        sudo apt install -y wget
        sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
        wget https://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
        sudo apt update
        sudo apt install python3-shapely python3-yaml python3-requests \
        -y
    - name: setup
      run: |
        mkdir -p ws_rmf/src
        cd ws_rmf/src
        git clone https://github.com/osrf/traffic_editor
        git clone https://github.com/osrf/rmf_core
        
    - name: checkout
      uses: actions/checkout@v2
      with:
        path: ws_rmf/src/rmf_schedule_visualizer

    - name: ros-deps
      run: |
        cd ws_rmf
        rosdep update
        rosdep install --from-paths src --ignore-src --rosdistro foxy -yr
    - name: build
      shell: bash
      run: |
        cd ws_rmf
        source /opt/ros/foxy/setup.bash
        colcon build --cmake-args -DCMAKE_BUILD_TYPE=RELEASE --packages-up-to visualizer
